### ISSUE TITLE
my_breadcrumb()

### ISSUE THREAD

**Issue by BooleanType** [ierhyna/goods-catalog#35]
Здравствуйте!
Для пробы создал один товар, но как-то запамятовал связать его с определённой категорией. Вот что вылезло:
`
Warning: Invalid argument supplied for foreach() in Z:\home\wp\www\wp-content\plugins\goods-catalog\inc\breadcrumbs.php on line 67
`
Ясно, что плагин <em>подразумевает</em> распределение товаров по категориям, но забывчивость пользователей-"непрограммистов" нельзя оставить в стороне. :)
Решение очевидно:
![default](https://cloud.githubusercontent.com/assets/10816818/6007576/f9f17382-ab23-11e4-97ff-76c6ac07492f.JPG)
Также, честно говоря, не совсем понял необходимость в этой же ф-ции условия-"обёртки":
`if (is_single() || is_tax()) {`
Одно из этих условий внутри "обёртки" всё равно выполнится, или она для наглядности?

**Comment by ierhyna** [comment]
Здравствуйте,
Спасибо за комментарий, да, действительно эту функцию надо было переписать. Добавила Ваши изменения в коммит, и включу в следующей версии плагина в репозиторий wp.
