### ISSUE TITLE
get_the_product_price()

### ISSUE THREAD

**Issue by romanxbayramov** [ierhyna/goods-catalog#56]
Указывается параметр префикса перед выводом цены
```php
function get_the_product_price( $title = '', $before = '<p class="goods-price-single">', $after = '</p>' ) {
```
Но потом он перезаписывается
```php
if ((isset($gc_price)) && ($gc_price != '')) { // show fields values
    $title = __('Price:', 'goods-catalog');
```

Получается, что параметр $title у функции захардкорен и невозможно указать какие-либо свои значения. Всегда выводится "Цена:" перед ценником. С $before и $after подобной мелкой ошибки не наблюдается.
Из-за данного бага не получается убрать все ненужное и вывести чистую строку цены без HTML-мусора.

```php
echo get_the_product_price( '', '', '' );
```

**Comment by ierhyna** [comment]
Добрый день, спасибо, сможете ли сделать пулл-реквест?

**Comment by romanxbayramov** [comment]
#58

**Comment by ierhyna** [comment]
Спасибо большое! Я потестирую, если все будте работать, выпущу в новой версии на выходных 👍

**Comment by ierhyna** [comment]
Смерджила пулл реквест, большое спасибо!
